### ISSUE TITLE
demo运行出错了

### ISSUE THREAD

**Issue by qinhuaihe** [HeskeyBaozi/umi-plugin-mobx#2]
运行demo的时候报了这个错.
`Error: MobX injector: Store 'users' is not available! Make sure it is provided by some Provider`

**Comment by qinhuaihe** [comment]
1. 我想把这个整合进 `antd-pro v2`里面来用, 用的是配置式的路由,请问是不是也要配置`umi-plugin-route`? 
2. `umi` 里面的`dva`里的model既可以是`models`文件夹里的文件, 也可以是`model.j|ts`文件的, 对应这个是`stores`文件夹和`store.j|ts`文件吗?

**Comment by qinhuaihe** [comment]
现在不支持`umi2.0`, 请问可以支持一下吗?

**Comment by HeskeyBaozi** [comment]
正在适配 `2.0` 版本开发中。该问题此周末修复。
1、目前是还需要 `umi-plugin-route`
2、是的

**Comment by antenando** [comment]
Very interested in the version compatible with the latest umi 2 as well. Good work! Keep it up!

**Comment by antenando** [comment]
@HeskeyBaozi can we take a look in your `dev` branch with the support for umi 2? 

thanks

**Comment by xiaohuoni** [comment]
@antenando 这里有一个js版本的，支持umi@2 https://github.com/umijs/umi-plugin-mobx-state-tree
欢迎试用

**Comment by antenando** [comment]
Thanks so much! Can't wait to get home and test it! My best regards and congrats again on the amazing work!
